### ISSUE TITLE
'Shop Now' button not working. TypeError: Cannot destructure property 'image' of 'product' as it is null

### ISSUE THREAD

**Issue by JohnTan38** [adrianhajdin/ecommerce_sanity_stripe#121]
TypeError: Cannot destructure property 'image' of 'product' as it is null.
    at ProductDetails (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\.next\server\pages\product\[slug].js:35:5)
    at d (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at b.render (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at b.read (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\node_modules\next\dist\server\render.js:751:45)
    at Object.defaultGetInitialProps (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\node_modules\next\dist\server\render.js:389:51)
    at Document.getInitialProps (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\.next\server\pages\_document.js:604:16)
    at Object.loadGetInitialProps (C:\Users\guest_dpdq7co\ecommerce_sanity_stripe\node_modules\next\dist\shared\lib\utils.js:69:29)

**Comment by amiii123malviya** [comment]
Hello,

Is this issue still active?
I would like to work on this.

Best Regards.

**Comment by JohnTan38** [comment]
Dear Sir
Yes still open. Please suggest / write code. Thank you very much in advance
